'''
get_artist_list.py

Fetches Top-Artists from Last.fm Charts and saves them as:
    - src/scripts/artists.py ← Python list, imported by other scripts
    - data/artists_list.csv ← CSV backup
    
Each page fetched through chart.gettopartists returns up to 50 artists. We fetch multiple pages to build a larger list.
'''

import requests
import pandas as pd
import time
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

API_KEY = os.getenv("LASTFM_API_KEY")
BASE_URL = "https://ws.audioscrobbler.com/2.0/"

def get_top_artists(pages=10):
    """
    Fetch a global Top Artists list from Last.fm charts.
    
    Args:
        pages (int): Number of pages to fetch (each page contains up to 50 artists).
    
    Returns:
        list: List of unique artist names.
    """
    all_artists = []

    for page in range(1, pages + 1):
        print(f"  Page {page}/{pages}...")
        try:
            response = requests.get(BASE_URL, params={
                "method": "chart.gettopartists",
                "api_key": API_KEY,
                "format": "json",
                "limit": 50,
                "page": page,
            }, timeout=10)
            data = response.json()
            artists = data.get("artists", {}).get("artist", [])
            for artist in artists:
                name = artist.get("name", "").strip()
                if name:
                    all_artists.append(name)
        except Exception as e:
            print(f"Page {page} failed: {e}")
        time.sleep(0.3)

    return all_artists


# Run
print("Fetching Top-Artists from Last.fm Charts...")
artists = get_top_artists(pages=10)  # Fetching up to 500 artists

# Remove duplicates while preserving order
seen = set()
unique_artists = []
for artist in artists:
    if artist not in seen:
        seen.add(artist)
        unique_artists.append(artist)

print(f"Collected {len(unique_artists)} unique artists")

# Save Python list (importable by other scripts)
with open("src/scripts/artists.py", "w", encoding="utf-8") as f:
    f.write("# Auto-generated by get_artists_list.py\n")
    f.write("# Source: Last.fm Top-Artists (chart.gettopartists)\n\n")
    f.write("ARTISTS = [\n")
    for artist in unique_artists:
        escaped = artist.replace("\\", "\\\\").replace('"', '\\"')
        f.write(f'    "{escaped}",\n')
    f.write("]\n")

print("Saved: src/scripts/artists.py")

# Save CSV backup
os.makedirs("data", exist_ok=True)
pd.DataFrame({"name": unique_artists}).to_csv("data/raw/artists_list.csv", index=False)
print("Saved: data/artists_list.csv")

print(f"First 10 artists:")
for artist in unique_artists[:10]:
    print(f"  {artist}")