'''
get_artist_list.py

Fetches Top-Artists from Last.fm Charts und saves them as:
    - src/scripts/artists.py ← Python list, impported by other scripts
    - data/artists_list.csv ← CSV backup
    
Each page fetched through chart.gettopartists returns up to 50 artists. We fetch multiple pages to build a larger list.  
'''
import requests
import pandas as pd
import time
import os
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.getenv("LASTFM_API_KEY")
BASE_URL = "https://ws.audioscrobbler.com/2.0/"


def get_top_artists(pages=10):
    """
    Fetch a global Top Artists list from Last.fm charts.
    """
    all_artists = []

    for page in range(1, pages + 1):
        print(f"  Seite {page}/{pages}...")
        try:
            r = requests.get(BASE_URL, params={
                "method": "chart.gettopartists",
                "api_key": API_KEY,
                "format": "json",
                "limit": 50,
                "page": page,
            }, timeout=10)
            data = r.json()
            artists = data.get("artists", {}).get("artist", [])
            for a in artists:
                name = a.get("name", "").strip()
                if name:
                    all_artists.append(name)
        except Exception as e:
            print(f"Page {page} failed: {e}")
        time.sleep(0.3)

    return all_artists


# Run
print("Fetching Top-Artists from Last.fm Charts...")
artists = get_top_artists(pages=10)  # = 500 artists

# Remove duplicates while preserving order
seen = set()
artists_unique = []
for a in artists:
    if a not in seen:
        seen.add(a)
        artists_unique.append(a)

print(f"Collected {len(artists_unique)} unique artists")

# Write python list (importable by other scripts)
with open("src/scripts/artists.py", "w", encoding="utf-8") as f:
    f.write("# Auto-generated by get_artists_list.py\n")
    f.write("# Source: Last.fm Top-Artists (chart.gettopartists)\n\n")
    f.write("ARTISTS = [\n")
    for name in artists_unique:
        escaped = name.replace("\\", "\\\\").replace('"', '\\"')
        f.write(f'    "{escaped}",\n')
    f.write("]\n")

print("Saved: src/scripts/artists.py")

# Write CSV backup
os.makedirs("data", exist_ok=True)
pd.DataFrame({"name": artists_unique}).to_csv("data/raw/artists_list.csv", index=False)
print("Saved: data/artists_list.csv")

print(f"\First 10 artists:")
for a in artists_unique[:10]:
    print(f"  {a}")
