import streamlit as st
from components.styles import apply_styles
from components.navbar import render_navbar
from components.glossary import apply_glossary_styles, tt

st.set_page_config(
    page_title="About Us — From Streams to Stages",
    page_icon="👥",
    layout="wide",
    initial_sidebar_state="collapsed",
)
apply_styles()
render_navbar()
apply_glossary_styles()

st.markdown("""
<div class="page-header">
    <h1>👥 About Us</h1>
    <p>The team behind this project</p>
</div>
""", unsafe_allow_html=True)

# ── Project Description ────────────────────────────────────────────────────
st.markdown("""
<div style="
    background: #161c2d;
    border: 1px solid #232840;
    border-radius: 16px;
    padding: 40px 48px;
    margin-bottom: 32px;
    max-width: 860px;
">
    <h2 style="color:#818cf8 !important; font-size:1.4rem; margin:0 0 20px 0;">
        A Data Science Project — 5th Semester
    </h2>
    <p style="color:#cbd5e1 !important; font-size:1.05rem; line-height:1.8; margin:0 0 20px 0;">
        We are four students of Computer Science and Business Informatics at
        <strong style="color:#f1f5f9 !important;">Christian-Albrechts-Universität zu Kiel</strong>,
        and developed this project as part of the Data Science praktikum in our fifth semester.
    </p>
    <p style="color:#cbd5e1 !important; font-size:1.05rem; line-height:1.8; margin:0 0 20px 0;">
        The central question of this project is straightforward in its formulation,
        but complex in its analysis:
        <em style="color:#818cf8 !important;">Can digital streaming data predict how and where
        artists go on tour?</em> More specifically, we investigated whether the listening patterns
        generated by millions of users on Last.fm and Spotify reflect the physical reality
        of concert touring.
    </p>
    <p style="color:#cbd5e1 !important; font-size:1.05rem; line-height:1.8; margin:0;">
        The project was motivated by a broader interest in the relationship between
        digital music consumption and the live music industry — an area where
        large-scale data analysis can offer insights that are difficult to obtain otherwise.
    </p>
</div>
""", unsafe_allow_html=True)

# ── Data Sources ───────────────────────────────────────────────────────────
st.markdown('<div class="section-title">📡 Data Sources</div>', unsafe_allow_html=True)

sources = [
    {
        "icon": "🎧",
        "name": "Last.fm API",
        "desc": "Listener counts, play counts, top tracks, and geographic popularity per country"
    },
    {
        "icon": "🎟️",
        "name": "Ticketmaster API",
        "desc": "Concert data including cities, countries, dates, and capital city status (2023–2026)"
    },
    {
        "icon": "🌍",
        "name": "RestCountries",
        "desc": "Country information dataset providing capital city data for all countries worldwide, used in the capital city analysis"
    },
    {
        "icon": "🗺️",
        "name": "Spotify Chart Data",
        "desc": "Weekly chart data from February 2023 to February 2026, used for chart artist classification"
    },
]

s_cols = st.columns(2)
for i, src in enumerate(sources):
    with s_cols[i % 2]:
        st.markdown(f"""
        <div class="insight-card" style="margin-bottom:12px;">
            <h4>{src['icon']} {src['name']}</h4>
            <p>{src['desc']}</p>
        </div>
        """, unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)

# ── Data Collection Note ───────────────────────────────────────────────────
st.markdown("""
<div class="methodology-note">
    <p>
    <strong>Note on data collection:</strong>
    The original project plan included the use of the Spotify Web API (followers, popularity score).
    However, due to API access restrictions introduced in February 2026 that removed these fields
    in Development Mode, <strong>Last.fm listener counts and play counts</strong> were used
    as alternative popularity proxies. Last.fm metrics are widely used in academic music research
    and have been shown to correlate strongly with cross-platform popularity indicators.
    </p>
</div>
""", unsafe_allow_html=True)
